### ISSUE TITLE
Version 4.5.5 - bot gets stuck in BBase

### ISSUE THREAD

**Issue by KiRZeN** [boludoz/AIO-Mod#57]
It gets stuck in different ways, once opening the laboratory, again just looking at its status, open the chat and stay that way, it doesn't give any error therefore I can't give you more information, I don't know if it just happens to me , I have disabled all the options in BBase and it continues to happen, I will go back to the previous version because I am not able to make it work, as always thank you very much for your work, it has been a long time since I contacted you due to an error.

All the best.

**Comment by boludoz** [comment]
Do you have discord?

**Comment by KiRZeN** [comment]
Yes.

**Comment by KiRZeN** [comment]
[21:35:47] Builder Base Village Report
[21:35:56] Builder Base Village Report
[21:36:01] Builder Base Village Report
[21:36:09] Builder Base Village Report
[21:36:14] Builder Base Village Report
[21:36:16] Builder Base Attack Zoomout

**Comment by boludoz** [comment]
This checks the resources, there is no other way brother, this is also done by the main village, I'll see what I can do.

**Comment by KiRZeN** [comment]
I know, well actually when it gets stuck is in the Builder Base Attack Zoomout action, I'm sorry I can't give you more details, in version 4.5.4 it works without problems, I'm with it right now, I hope it helps you, Greetings and thank you.

**Comment by supermopf** [comment]
Hey there, 

since I have the same issue, I recorded a small video to clarify what the bot does:

https://drive.google.com/uc?id=1wA4NkWMhLqUBhDXqaVL9Fp6DsYeijVE9

The bot clicks after a few zoomout attempts to the left of the screen and opens the chat.
Then it tries more spots and clicks around but since it is not in the base anymore, its just looping opening the my clan page and closing it again.
 
In the "normal" version of the bot the builder base works very well. Maybe have a look into it.

Have a nice day,
Victor

**Comment by KiRZeN** [comment]
Good, thanks for the new update, tell you that the problem persists, only now it stays in Zooming Out, it manages to pass but it costs more than 10 minutes each time it stays there, I can not tell you more than, it does the same as in The video that they showed you in the previous comment, open the chat, and start touching the donate button, look at chat profiles and others, at least now after a long time manages to advance.

All the best.

**Comment by boludoz** [comment]
Strange, I have reversed everything.

**Comment by boludoz** [comment]
https://discord.gg/WZQEa3Kg
